github.com:
    git_protocol: ssh
    users:
        The-Briel-Deal:
            oauth_token: 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
    user: The-Briel-Deal
    oauth_token: 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
