default_category = "AllCategories"
default_filter = "NoFilter"
default_sort = "Date"
default_search = ""
theme = "Default"
source = "NyaaHtml"
download_client = "transmission"
date_format = "%Y-%m-%d %H:%M"
base_url = "https://nyaa.si/"
timeout = 30

[client.command]
cmd = "curl \"{torrent}\" > ~/{file}"
shell_cmd = "sh -c"

[client.transmission]
base_url = "http://localhost:9091/transmission/rpc"
